FROM ubuntu:18.04

# my basic dev env setting

RUN apt-get update
RUN apt-get install -y git vim build-essential cmake python3-dev python3-pip
RUN cd ~; git clone https://github.com/tim-ts-chu/linux-config.git
RUN ~/linux-config/install.sh
RUN mkdir /root/_UbuntuSync

# basic python module
RUN pip3 install numpy matplotlib 

